project:
  type: website
  output-dir: _site

website:
  title: "DEDALUS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: boards.qmd
        text: Hardware
      - href: modeling.qmd
        text: Digital Twin
      - href: motion.qmd
        text: Motion & Integration

    right:
      - icon: github
        href: https://https://github.com/DEDALUS-5x

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    
    number-sections: true
    toc: true
    lightbox: true
    code-copy: true


